### ISSUE TITLE
actix-web using dieseil is slowest possible combination

### ISSUE THREAD

**Issue by dunnock** [evoxmusic/twitter-clone-rust#1]
If speaking of performance, this is not ideal combination at all. Which can be seen in techempowerbenchmark. I would suggest to use tokio-postgres or deadpool-postgres, I ve spent quite a lot of time benchmarking that https://github.com/dunnock/actix-node-benchmark/tree/master/actix-bench
And https://medium.com/@maxsparr0w/performance-of-node-js-compared-to-actix-web-37f20810fb1a

**Comment by evoxmusic** [comment]
Thanks @dunnock , good catch, I was wondering if they were an async driver available. I'm gonna read your article.

**Comment by dunnock** [comment]
Cool, closing this as it was only advice

**Comment by evoxmusic** [comment]
@dunnock great article BTW, I will make a note to my part 1 concerning your advice 👍. 
I will include the bench of this async driver as well for part 2. 

Stay safe. Romaric.
